-- Host: localhost:3306
-- Generation Time: Sep 25, 2016 at 10:48 PM
-- Server version: 5.6.33
-- PHP Version: 5.6.20

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `tblQuotes` (
  `quoteID` int(10) NOT NULL AUTO_INCREMENT,
  `author` varchar(100) NOT NULL,
  `quote` text NOT NULL,
  `permalink` varchar(100),
  `image` varchar(100) NOT NULL,
  PRIMARY KEY (`quoteID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Bill Sempf','QA Engineer walks into a bar. Orders a beer. Orders 0 beers. Orders 999999999 beers. Orders a lizard. Orders -1 beers. Orders a sfdeljknesv.','http://quotes.stormconsultancy.co.uk/quotes/44','image1.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Phil Karlton','There are only two hard things in Computer Science: cache invalidation, naming things and off-by-one errors.','http://quotes.stormconsultancy.co.uk/quotes/43','image2.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Jeff Atwood','In software, we rarely have meaningful requirements. Even if we do, the only measure of success that matters is whether our solution solves the customer’s shifting idea of what their problem is.','http://quotes.stormconsultancy.co.uk/quotes/42','image3.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Robert Sewell','If Java had true garbage collection, most programs would delete themselves upon execution.','http://quotes.stormconsultancy.co.uk/quotes/41','image4.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Bjarne Stroustrup','In C++ it’s harder to shoot yourself in the foot, but when you do, you blow off your whole leg.','http://quotes.stormconsultancy.co.uk/quotes/39','image5.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Alan Kay','Most software today is very much like an Egyptian pyramid with millions of bricks piled on top of each other, with no structural integrity, but just done by brute force and thousands of slaves.','http://quotes.stormconsultancy.co.uk/quotes/38','image6.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Larry DeLuca','I’ve noticed lately that the paranoid fear of computers becoming intelligent and taking over the world has almost entirely disappeared from the common culture.  Near as I can tell, this coincides with the release of MS-DOS.','http://quotes.stormconsultancy.co.uk/quotes/37','image7.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Mark Gibbs','No matter how slick the demo is in rehearsal, when you do it in front of a live audience, the probability of a flawless presentation is inversely proportional to the number of people watching, raised to the power of the amount of money involved.','http://quotes.stormconsultancy.co.uk/quotes/36','image8.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Henry Petroski','The most amazing achievement of the computer software industry is its continuing cancellation of the steady and staggering gains made by the computer hardware industry.','http://quotes.stormconsultancy.co.uk/quotes/35','image9.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Jeremy S. Anderson','There are two major products that come out of Berkeley: LSD and UNIX.  We don’t believe this to be a coincidence.','http://quotes.stormconsultancy.co.uk/quotes/34','image10.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Jamie Zawinski','Linux is only free if your time has no value.','http://quotes.stormconsultancy.co.uk/quotes/32','image11.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Richard Moore','The difference between theory and practice is that in theory, there is no difference between theory and practice.','http://quotes.stormconsultancy.co.uk/quotes/30','image12.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Bjarne Stroustrup','There are only two kinds of programming languages: those people always bitch about and those nobody uses.','http://quotes.stormconsultancy.co.uk/quotes/28','image13.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Donald Knuth','Beware of bugs in the above code; I have only proved it correct, not tried it.','http://quotes.stormconsultancy.co.uk/quotes/27','image14.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Tom Van Vleck','We know about as much about software quality problems as they knew about the Black Plague in the 1600s. We’ve seen the victims’ agonies and helped burn the corpses. We don’t know what causes it; we don’t really know if there is only one disease. We just suffer — and keep pouring our sewage into our water supply.','http://quotes.stormconsultancy.co.uk/quotes/26','image15.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('N.J. Rubenking','Writing the first 90 percent of a computer program takes 90 percent of the time. The remaining ten percent also takes 90 percent of the time and the final touches also take 90 percent of the time.','http://quotes.stormconsultancy.co.uk/quotes/25','image16.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('C. A. R. Hoare','There are two ways of constructing a software design; one way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies. The first method is far more difficult.','http://quotes.stormconsultancy.co.uk/quotes/24','image17.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('James O. Coplien','You should name a variable using the same care with which you name a first-born child.','http://quotes.stormconsultancy.co.uk/quotes/23','image18.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Fred Brooks','Einstein argued that there must be simplified explanations of nature, because God is not capricious or arbitrary. No such faith comforts the software engineer.','http://quotes.stormconsultancy.co.uk/quotes/22','image19.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Douglas Adams','I love deadlines. I like the whooshing sound they make as they fly by.','http://quotes.stormconsultancy.co.uk/quotes/19','image20.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Keith Bostic','Perl – The only language that looks the same before and after RSA encryption.','http://quotes.stormconsultancy.co.uk/quotes/18','image21.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Albert Einstein','Two things are infinite: the universe and human stupidity; and I’m not sure about the universe.','http://quotes.stormconsultancy.co.uk/quotes/17','image22.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Yogi Berra','In theory, theory and practice are the same. In practice, they’re not.','http://quotes.stormconsultancy.co.uk/quotes/16','image23.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('E. W. Dijkstra','It is practically impossible to teach good programming style to students that have had prior exposure to BASIC. As potential programmers, they are mentally mutilated beyond hope of regeneration.','http://quotes.stormconsultancy.co.uk/quotes/15','image24.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('E. W. Dijkstra','If debugging is the process of removing software bugs, then programming must be the process of putting them in.','http://quotes.stormconsultancy.co.uk/quotes/14','image25.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Mitch Ratcliffe','A computer lets you make more mistakes faster than any other invention in human history, with the possible exceptions of handguns and tequila.','http://quotes.stormconsultancy.co.uk/quotes/13','image26.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Bjarne Stroustrup','I have always wished for my computer to be as easy to use as my telephone; my wish has come true because I can no longer figure out how to use my telephone.','http://quotes.stormconsultancy.co.uk/quotes/12','image27.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Ovidiu Platon','I don’t care if it works on your machine! We are not shipping your machine!','http://quotes.stormconsultancy.co.uk/quotes/11','image28.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Rich Cook','Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning.','http://quotes.stormconsultancy.co.uk/quotes/10','image29.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Rick Osborne','Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.','http://quotes.stormconsultancy.co.uk/quotes/9','image30.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Charles Babbage','On two occasions I have been asked, ‘Pray, Mr. Babbage, if you put into the machine wrong figures, will the right answers come out?’ I am not able rightly to apprehend the kind of confusion of ideas that could provoke such a question.”','http://quotes.stormconsultancy.co.uk/quotes/8','image31.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Jon Ribbens','PHP is a minor evil perpetrated and created by incompetent amateurs, whereas Perl is a great and insidious evil, perpetrated by skilled but perverted professionals.','http://quotes.stormconsultancy.co.uk/quotes/7','image32.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Bill Gates','Measuring programming progress by lines of code is like measuring aircraft building progress by weight.','http://quotes.stormconsultancy.co.uk/quotes/6','image33.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Brian Kernighan','Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.','http://quotes.stormconsultancy.co.uk/quotes/5','image34.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Jamie Zawinski','Some people, when confronted with a problem, think “I know, I’ll use regular expressions.” Now they have two problems.','http://quotes.stormconsultancy.co.uk/quotes/4','image35.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Hofstadter’s Law','It always takes longer than you expect, even when you take into account Hofstadter’s Law.','http://quotes.stormconsultancy.co.uk/quotes/3','image36.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('Edward V Berard','Walking on water and developing software from a specification are easy if both are frozen.','http://quotes.stormconsultancy.co.uk/quotes/2','image37.png');
INSERT INTO `tblQuotes`(`author`,`quote`,`permalink`,`image`) VALUES ('C. A. R. Hoare','We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil.','http://quotes.stormconsultancy.co.uk/quotes/1','image38.png');
